name: global_event_bus
description: A high-performance, type-safe global event bus system for Flutter applications with priority support, batch processing, and comprehensive logging.
version: 1.0.1
homepage: https://gitee.com/peiduo_734386/global_event_bus
repository: https://gitee.com/peiduo_734386/global_event_bus
issue_tracker: https://gitee.com/peiduo_734386/global_event_bus/issues

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

