name: global_event_bus
description: A high-performance, type-safe global event bus system for Flutter applications with priority support, batch processing, and comprehensive logging.
version: 0.0.6
homepage: https://github.com/pei-duo/global_event_bus
repository: https://github.com/pei-duo/global_event_bus
issue_tracker: https://github.com/pei-duo/global_event_bus/issues

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.global_event_bus
        pluginClass: GlobalEventBusPlugin
      ios:
        pluginClass: GlobalEventBusPlugin
      linux:
        pluginClass: GlobalEventBusPlugin
      macos:
        pluginClass: GlobalEventBusPlugin
      windows:
        pluginClass: GlobalEventBusPluginCApi
      web:
        pluginClass: GlobalEventBusWeb
        fileName: global_event_bus_web.dart
